spring.data.mongodb.uri=mongodb://mongo:mongo@localhost:27017/product_service

# spring.data.mongodb.host=localhost
# spring.data.mongodb.port=27017
# spring.data.mongodb.database=product_service
# spring.data.mongodb.username=mongo
# spring.data.mongodb.password=mongo

# spring.jpa.hibernate.ddl-auto=create
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.format_sql=true

server.port=8083

eureka.client.serviceUrl.defaultZone=http://admin:admin@localhost:8761/eureka
# eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
spring.application.name=product-service

